version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  web:
    image: evangribov/yamdb
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
    restart: always
    depends_on:
      - db
    env_file: 
      - .env

  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static
      - mediafiles:/media
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
