version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api_yamdb/.env
  
  web:
    image: ayztuva/yamdb
    volumes:
      - staticfiles:/code/static
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    env_file: 
      - ./api_yamdb/.env

  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static/
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
